#!/bin/bash

readonly ERROR_PREFIX=$'---- ERROR -----------------------------------------------------\n\n'
readonly INDENTATION="    "
readonly NODE="Node.js"
readonly NPM="npm"
readonly URL_NODE="https://nodejs.org"
readonly MSG_NOT_WRITTEN="Userscript file could not be assembled."
readonly MSG_TRY_THIS=$'You can try this to fix this problem:\n'
readonly DIR_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR_NODE_MODULES="node_modules"
readonly DIR_BUILD=".userscripter/build"
readonly DIR_SRC="src"
readonly DIR_WEBPACK="$DIR_NODE_MODULES/webpack"
readonly FILE_WEBPACK_CONFIG="webpack.config.js"
readonly FILE_WEBPACK_OUTPUT=".webpack-output.js"
readonly FILE_TS_CONFIG="tsconfig.json"
readonly FILE_ENTRY="$DIR_SRC/main.ts"
readonly FLAG_PRODUCTION="--production"
readonly FLAG_DEBUG="--debug"
readonly CMD_WEBPACK="$DIR_NODE_MODULES/.bin/webpack"
readonly CMD_INIT="./init"
readonly CMD_BUILD="./build"
readonly CMD_INSTALL="npm install"
readonly CMD_REBUILD="npm rebuild"
readonly CMD_DELETE_NODE_MODULES="rm -rf node_modules"

cd "$DIR_ROOT"

function printHelp() {
    echo "Usage: build [$FLAG_PRODUCTION] [$FLAG_DEBUG]"
    echo
    echo "Examples:"
    echo
    echo "General development:"
    echo
    echo "${INDENTATION}build"
    echo
    echo "With source maps:"
    echo
    echo "${INDENTATION}build --debug"
    echo
    echo "With transpilation and minification:"
    echo
    echo "${INDENTATION}build --production"
    echo
}

# Help message:
for arg in "$@"; do
    if [ "$arg" == "--help" -o "$arg" == "-h" ]; then
        printHelp
        exit 0
    fi
done

mode=""
# Determine mode:
for arg in "$@"; do
    if [ "$arg" == "$FLAG_DEBUG" ]; then
        mode="$FLAG_DEBUG"
    fi
done
# --production overrides --debug:
for arg in "$@"; do
    if [ "$arg" == "$FLAG_PRODUCTION" ]; then
        mode="$FLAG_PRODUCTION"
    fi
done

# Check if source code directory exists:
if [ ! -d $DIR_SRC ]; then
    echo
    echo "$ERROR_PREFIX""Source code directory not found."
    echo
    echo "I couldn't find $DIR_SRC/ in this directory."
    echo
    echo "$MSG_TRY_THIS"
    echo "$INDENTATION$CMD_INIT"
    echo
    exit 1
fi

# Check if entry file exists:
if [ ! -f $FILE_ENTRY ]; then
    echo
    echo "$ERROR_PREFIX""Entry file not found."
    echo
    echo "I couldn't find $FILE_ENTRY in this directory."
    echo
    echo "$MSG_TRY_THIS"
    echo "$INDENTATION$CMD_INIT"
    echo
    exit 2
fi

# Check if Node.js exists:
if [ "$(type node)" == "" ]; then
    echo
    echo "$ERROR_PREFIX$NODE not found."
    echo
    echo "It seems that $NODE is not installed. You can find it here:"
    echo
    echo "$INDENTATION$URL_NODE"
    echo
    exit 10
fi

# Check if npm exists:
if [ "$(type npm)" == "" ]; then
    echo
    echo "$ERROR_PREFIX$NPM not found."
    echo
    echo "It seems that $NPM is not installed. You can try reinstalling $NODE to fix this problem. $NODE can be found here:"
    echo
    echo "$INDENTATION$URL_NODE"
    echo
    exit 10
fi

# Check if node_modules exists:
if [ ! -e $DIR_NODE_MODULES ]; then
    echo
    echo "$ERROR_PREFIX$DIR_NODE_MODULES/ not found."
    echo
    echo "I couldn't find $DIR_NODE_MODULES/ in this directory. This probably means that the necessary dependencies are not installed."
    echo
    echo "$MSG_TRY_THIS"
    echo "$INDENTATION$CMD_INSTALL"
    echo
    exit 11
fi

# Check if Webpack exists:
if [ ! -e $CMD_WEBPACK ] || [ ! -e $DIR_WEBPACK ]; then
    echo "$ERROR_PREFIX""Webpack not found."
    echo
    echo "I need Webpack to be installed locally, i.e. in $DIR_NODE_MODULES/ in this directory, but I couldn't find it there."
    echo
    echo "$MSG_TRY_THIS"
    echo "$INDENTATION$CMD_INSTALL"
    echo
    echo "If that doesn't work, you can try this:"
    echo
    echo "$INDENTATION$CMD_REBUILD"
    echo
    echo "And if that doesn't work, you can try this:"
    echo
    echo "$INDENTATION$CMD_DELETE_NODE_MODULES"
    echo "$INDENTATION$CMD_INSTALL"
    echo
    exit 12
fi

# Check if Webpack config file exists:
if [ ! -e $FILE_WEBPACK_CONFIG ]; then
    echo "$ERROR_PREFIX""Webpack config file not found."
    echo
    echo "I need the file $FILE_WEBPACK_CONFIG in order to build, but I couldn't find it in this directory."
    echo
    exit 13
fi

# Check if TypeScript config file exists:
if [ ! -e $FILE_TS_CONFIG ]; then
    echo "$ERROR_PREFIX""TypeScript config file not found."
    echo
    echo "I need the file $FILE_TS_CONFIG in order to build, but I couldn't find it in this directory."
    echo
    exit 14
fi

# Check config and metadata and exit if they are invalid:
node $DIR_BUILD/prepare.js
if [ $? -gt 0 ]; then
    echo
    echo
    echo "Config/metadata validation failed. $MSG_NOT_WRITTEN"
    echo
    exit 20
fi

echo

# Run Webpack:
if [ "$mode" == "$FLAG_PRODUCTION" ]; then
    echo "Building for production..."
    $CMD_WEBPACK --env.production
elif [ "$mode" == "$FLAG_DEBUG" ]; then
    echo "Building with source maps..."
    $CMD_WEBPACK --devtool inline-source-map
else
    echo "Building for development... (use $FLAG_PRODUCTION to build with transpilation and minification)"
    $CMD_WEBPACK
fi

# Exit if Webpack build failed:
if [ $? -gt 0 ]; then
    echo
    echo "Webpack build failed. $MSG_NOT_WRITTEN"
    echo
    exit 30
fi

# Assemble userscript:
node $DIR_BUILD/assemble.js

# Exit if assembly failed:
if [ $? -gt 0 ]; then
    echo
    echo "Userscript assembly failed. $MSG_NOT_WRITTEN"
    echo
    exit 40
fi
