name: Commit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
