name: PR
on:
  pull_request: # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
